name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Alpine Linux x86
      uses: jirutka/setup-alpine@v1
      with:
        arch: x86
    
    - name: Install clang
      run: apk add clang make
      shell: alpine.sh --root {0}

    - name: Run make
      run: make
      shell: alpine.sh {0}

    - name: Run main
      run: ./main
      shell: alpine.sh {0}
